### ISSUE TITLE
eShopOnContainers deploys successfully, but app is not functional

### ISSUE THREAD

**Issue by lakshmimsft** [radius-project/samples#58]
Description: eShop sample on k3d has issues. 

Notes: This bicep will not run on an ARM64 Mac. (https://github.com/project-radius/radius/issues/2980)
Attempted to deploy the bicep on Codespaces before v0.13 release.
After updating Redis connectionstring to remove 'ssl=True', the deployment looks successful and homepage loads but the site is not functional.

- [x] radius-project/radius#89
- [x] radius-project/radius#90
- [x] radius-project/radius#91
- [x] radius-project/radius#92
https://github.com/project-radius/samples/blob/edge/reference-apps/eshop/iac/app.bicep
